services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: restaurant_frontend
    restart: unless-stopped
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
